name: 'Run pup on a URL'
description: 'Read a URL and run pup on it'
inputs:
  url:
    description: 'The URL to read'
    required: true
  selector:
    description: 'The CSS selector to use'
    required: True
outputs:
  result:
    description: 'The result of the URL'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.url }}
    - ${{ inputs.selector }}
